name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build for Linux and Windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Build binary for Linux amd64
        run: |
          GOOS=linux GOARCH=amd64 go build -o psndownloader-linux-amd64 main.go

      - name: Build binary for Windows amd64
        run: |
          GOOS=windows GOARCH=amd64 go build -o psndownloader-windows-amd64.exe main.go

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: |
            psndownloader-linux-amd64
            psndownloader-windows-amd64.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: binaries

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: binaries/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

